name: Setup Server

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Amazon Linux container
        uses: docker://amazonlinux:latest

      - name: Run installation script
        run: |
          yum update -y
          yum install -y java-1.8.0-openjdk redis
          systemctl enable redis
          systemctl start redis
          
          # Install Filebeat
          rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
          cat <<EOF | tee /etc/yum.repos.d/elastic-7.x.repo
          [elastic-7.x]
          name=Elastic repository for 7.x packages
          baseurl=https://artifacts.elastic.co/packages/7.x/yum
          gpgcheck=1
          enabled=1
          gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
          EOF
          yum install -y filebeat
          systemctl enable filebeat
          systemctl start filebeat
          
          # Install MySQL 8.0
          yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
          yum install -y mysql-community-server
          systemctl enable mysqld
          systemctl start mysqld

      - name: Check service status
        run: |
          systemctl status redis
          systemctl status filebeat
          systemctl status mysqld
